### ISSUE TITLE
The bfs in /dev branch is not giving the path between the source and destination?

### ISSUE THREAD

**Issue by CeaSyProject** [ks5-dev/EscapeTheDungeon#1]
Can you please update this?

**Comment by ks5-dev** [comment]
I am currently working on this right now. I hope to finish implementing this feature this weekend. Here is the to-do list for this project:

1. Finish implementing the feature you mention. Creating a BFS algorithm to find the path between enemies and the players (rn they can pass through walls)
2. Improve gameplay, there is a visual bug that you can into a wall a bit, but I failed to debug it
3. Replace assets on opengameart.com with my own art.
